const $=id=>document.getElementById(id);const fields=["car_name","vehicle_style","entity_prefix","dashboard_path","geoapify_api_key","output_folder","refresh_interval","trigger_delay","language","notifications_enabled","notify_services"];let settings={},discovery={prefixes:[],notify_services:[]},catalog={};
const STRINGS={
  en:{tagline:"Premium vehicle images and Companion App notifications.",status_loading:"Loading",status_ready:"Connected",status_setup:"Setup required",status_error:"Needs attention",tab_vehicle:"Vehicle",tab_notifications:"Notifications",tab_appearance:"Appearance",tab_preview:"Preview",vehicle_head:"Vehicle connection",vehicle_sub:"Select the existing Leapmotor entities in Home Assistant.",discover:"Detect automatically",car_name_label:"Vehicle name",vehicle_style_label:"Vehicle appearance",entity_prefix_label:"Entity prefix",entity_prefix_placeholder:"Select or detect a vehicle",refresh_interval_label:"Refresh interval",seconds:"seconds",language_label:"Interface language",notifications_head:"Companion App notifications",notifications_sub:"Send one rendered parking notification to multiple devices.",notifications_toggle_label:"Enable notifications",notify_services_label:"Receiving devices",notify_services_hint:"Use Ctrl/Cmd to select multiple devices.",dashboard_path_label:"Dashboard path",trigger_delay_label:"Parking delay",appearance_head:"Images and maps",appearance_sub:"Choose where images are saved and optionally enable address lookup.",output_folder_label:"Output folder",geoapify_label:"Geoapify API key",geoapify_placeholder:"Optional",geoapify_notice:"The API key is stored only in the add-on's private data directory and is never included in images or logs.",preview_head:"Live preview",preview_sub:"Generate all six images using the current Home Assistant values.",render:"Render now",save:"Save configuration",saved:"Configuration saved",rendering:"Rendering images…",rendered:"Preview updated",found:(v,n)=>`Found ${v} vehicle(s) and ${n} device(s)`},
  nl:{tagline:"Premium voertuigafbeeldingen en Companion App-meldingen.",status_loading:"Laden",status_ready:"Verbonden",status_setup:"Instellen vereist",status_error:"Aandacht vereist",tab_vehicle:"Voertuig",tab_notifications:"Meldingen",tab_appearance:"Weergave",tab_preview:"Voorbeeld",vehicle_head:"Voertuigverbinding",vehicle_sub:"Selecteer de bestaande Leapmotor-entiteiten in Home Assistant.",discover:"Automatisch detecteren",car_name_label:"Voertuignaam",vehicle_style_label:"Voertuiguiterlijk",entity_prefix_label:"Entiteitsprefix",entity_prefix_placeholder:"Selecteer of detecteer een voertuig",refresh_interval_label:"Verversingsinterval",seconds:"seconden",language_label:"Interfacetaal",notifications_head:"Companion App-meldingen",notifications_sub:"Verstuur één gerenderde parkeermelding naar meerdere apparaten.",notifications_toggle_label:"Meldingen inschakelen",notify_services_label:"Ontvangende apparaten",notify_services_hint:"Gebruik Ctrl/Cmd om meerdere apparaten te selecteren.",dashboard_path_label:"Dashboardpad",trigger_delay_label:"Parkeervertraging",appearance_head:"Afbeeldingen en kaarten",appearance_sub:"Kies waar afbeeldingen worden opgeslagen en schakel optioneel adresopzoeking in.",output_folder_label:"Uitvoermap",geoapify_label:"Geoapify API-sleutel",geoapify_placeholder:"Optioneel",geoapify_notice:"De API-sleutel wordt alleen opgeslagen in de privé-datamap van de add-on en verschijnt nooit in afbeeldingen of logs.",preview_head:"Live voorbeeld",preview_sub:"Genereer alle zes afbeeldingen met de huidige Home Assistant-waarden.",render:"Nu renderen",save:"Configuratie opslaan",saved:"Configuratie opgeslagen",rendering:"Afbeeldingen renderen…",rendered:"Voorbeeld bijgewerkt",found:(v,n)=>`${v} voertuig(en) en ${n} apparaat/apparaten gevonden`},
};
function tr(key,...args){const s=STRINGS[$("language").value]||STRINGS.en;const value=s[key];return typeof value==="function"?value(...args):(value??key)}
function applyStrings(){const s=STRINGS[$("language").value]||STRINGS.en;document.querySelectorAll("[data-i18n]").forEach(element=>{const value=s[element.dataset.i18n];if(typeof value==="string")element.textContent=value});document.querySelectorAll("[data-i18n-placeholder]").forEach(element=>{const value=s[element.dataset.i18nPlaceholder];if(typeof value==="string")element.placeholder=value});const placeholderOption=$("entity_prefix").querySelector('option[value=""]');if(placeholderOption)placeholderOption.textContent=s.entity_prefix_placeholder}
async function api(path,options={}){const response=await fetch(`api/${path}`,options);const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||response.statusText);return body}
function selectOptions(element,values,selected){element.innerHTML="";values.forEach(value=>{const option=new Option(value,value);option.selected=(selected||[]).includes(value);element.add(option)})}
function populate(){selectOptions($("vehicle_style"),Object.keys(catalog),[settings.vehicle_style]);[...$("vehicle_style").options].forEach(option=>{const item=catalog[option.value];option.textContent=`${item.model} — ${item.colour}`});fields.forEach(id=>{const element=$(id);if(!element)return;if(element.type==="checkbox")element.checked=!!settings[id];else if(element.multiple)selectOptions(element,discovery.notify_services,settings[id]);else if(!["entity_prefix","vehicle_style"].includes(id))element.value=settings[id]??""});const prefixes=[...new Set([settings.entity_prefix,...discovery.prefixes].filter(Boolean))];$("entity_prefix").innerHTML='<option value="">Select or detect a vehicle</option>';prefixes.forEach(value=>$("entity_prefix").add(new Option(value,value,value===settings.entity_prefix,value===settings.entity_prefix)));applyStrings();syncNotificationFields()}
async function load(){try{[settings,discovery,catalog]=await Promise.all([api("settings"),api("discover"),api("catalog")]);populate();await status()}catch(error){message(error.message,true)}}
async function status(){try{const data=await api("status"),pill=$("statusPill");pill.className=`pill ${data.last_error?"error":data.configured?"ready":""}`;pill.querySelector("b").textContent=data.last_error?tr("status_error"):data.configured?tr("status_ready"):tr("status_setup")}catch{}}
function payload(){const result={};fields.forEach(id=>{const element=$(id);if(element.type==="checkbox")result[id]=element.checked;else if(element.multiple)result[id]=[...element.selectedOptions].map(option=>option.value);else if(element.type==="number")result[id]=Number(element.value);else result[id]=element.value});return result}
function message(text,error=false){$("message").textContent=text;$("message").style.color=error?"var(--danger)":"var(--muted)"}
function syncNotificationFields(){const enabled=$("notifications_enabled").checked;["notify_services","dashboard_path","trigger_delay"].forEach(id=>{const element=$(id);if(element)element.disabled=!enabled})}
$("notifications_enabled").addEventListener("change",syncNotificationFields);
document.querySelectorAll(".tabs button").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll(".tabs button,.panel").forEach(item=>item.classList.remove("active"));button.classList.add("active");$(button.dataset.tab).classList.add("active")}));
$("language").addEventListener("change",()=>{applyStrings();status()});
$("settingsForm").addEventListener("submit",async event=>{event.preventDefault();const button=event.submitter;button.disabled=true;try{const result=await api("settings",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload())});settings=result.settings;message(tr("saved"));await status()}catch(error){message(error.message,true)}finally{button.disabled=false}});
$("discoverButton").addEventListener("click",async()=>{const button=$("discoverButton");button.disabled=true;try{discovery=await api("discover");populate();message(tr("found",discovery.prefixes.length,discovery.notify_services.length))}catch(error){message(error.message,true)}finally{button.disabled=false}});
$("renderButton").addEventListener("click",async()=>{const button=$("renderButton");button.disabled=true;message(tr("rendering"));try{await api("render",{method:"POST"});const names=["overview","parked","charging","climate","tyres","security","dashboard_set"],stamp=Date.now();$("previewGrid").innerHTML=names.map(name=>`<div class="preview"><img src="api/image/${name}.png?v=${stamp}" alt="${name}"><b>${name}</b></div>`).join("");message(tr("rendered"))}catch(error){message(error.message,true)}finally{button.disabled=false}});load();setInterval(status,15000);
